### ISSUE TITLE
No Aplite-Optimized Tux PNG

### ISSUE THREAD

**Issue by ishotjr** [ishotjr/pw-dos#4]
### Summary

`#ifdef PBL_COLOR` should be used to specify an alternate resource for Aplite - [see `hcf` splash for example](https://github.com/ishotjr/pw-dos/blob/hcf/src/PebbleTutorial1.c#L28), and check out [HyperDither](http://www.tinrocket.com/hyperdither/) for image creation. :bowtie: :thought_balloon: 
### Steps to Repro
1. switch to any other watchface
2. switch back to `pw-bash`
3. observe non-optimized splash

![pebble-screenshot_2015-06-03_21-04-27](https://cloud.githubusercontent.com/assets/1594827/7974805/2b076c28-0a34-11e5-94d7-06955c9c6125.png)

Looks really cool on Basalt though! :grinning: 
### Technical Details
- Build version: https://github.com/ishotjr/pw-dos/commit/980460a3609e3e713327c9f4e1319ec1795f85f6
- Aplite running 2.9.1

**Comment by ishotjr** [comment]
Looks good! :bowtie: :+1: 

![pebble-screenshot_2015-06-04_21-07-06](https://cloud.githubusercontent.com/assets/1594827/7997646/7a028b4e-0afe-11e5-9fb5-f34eb20947b9.png)

**Comment by racerx** [comment]
Cool! I think I can fix those artifacts a bit.
