### ISSUE TITLE
"Floating" Cursor on cursor_timer_callback()

### ISSUE THREAD

**Issue by ishotjr** [ishotjr/pw-dos#6]
### Summary

Current `pw-bash` cursor position is still based on `pw-dos` UI.
### Steps to Repro
1. shake watch, or `pebble emu-tap --axis x --direction 1 --emulator {platform}`
2. observe "floating" cursor

![pebble-screenshot_2015-06-02_20-56-29](https://cloud.githubusercontent.com/assets/1594827/7975107/78aa8c4a-0a38-11e5-8bfc-7c0a97f75cb3.png)
### Technical Details
- Build version: https://github.com/ishotjr/pw-dos/commit/980460a3609e3e713327c9f4e1319ec1795f85f6
- Aplite running 2.9.1

**Comment by ishotjr** [comment]
@racerx Still seeing this in https://github.com/ishotjr/pw-dos/commit/7134ea31bfca8e8c16eee13b25629f109685bc20 - if you like, I can fix post-merge? :bowtie: :thought_balloon:

**Comment by racerx** [comment]
@ishotjr yes please fix post merge. ty :+1: :tiger: :cake:

**Comment by ishotjr** [comment]
@racerx Fixed!

![pw-bash-green-blink](https://cloud.githubusercontent.com/assets/1594827/8321138/4864d748-19f1-11e5-94dc-d996ee18f173.gif)
