### ISSUE TITLE
Bluetooth Disconnection Not Handled

### ISSUE THREAD

**Issue by ishotjr** [ishotjr/pw-dos#7]
### Summary

Bluetooth disconnection message is not displayed on disconnection (`update_time(-1)` not handled).
### Steps to Repro
1. Disconnect Pebble or disable Bluetooth
2. No visual indication is given to user via `update_time(-1)`

![pebble-screenshot_2015-06-02_20-58-56](https://cloud.githubusercontent.com/assets/1594827/7975199/aec8121a-0a39-11e5-9d9a-da04676ad8a8.png)
### Technical Details
- Build version: https://github.com/ishotjr/pw-dos/commit/980460a3609e3e713327c9f4e1319ec1795f85f6
- Aplite running 2.9.1

**Comment by racerx** [comment]
pebble emu-bt-connection --connected yes --emulator basalt
pebble emu-bt-connection --connected no --emulator basalt

pebble emu-bt-connection --connected yes --emulator aplite
pebble emu-bt-connection --connected no --emulator aplite

**Comment by ishotjr** [comment]
@racerx :blush: Oops, I tried to include emu references elsewhere, but forgot that the app/phone-based method described above couldn't be repro'd on the emulator! :bowtie:
